### ISSUE TITLE
How to create a function container image in a different language

### ISSUE THREAD

**Issue by guojian83** [direktiv/direktiv-apps#14]
Just wonder if there is any sample of creating a function container image in a different language?
If not, how can I do it?
I tried a couple of ways myself by using powershell scripts, however, it ran into the following error in the end:
_Action crashed due to an internal error: Post "http://workflow-13418411225808356493-jsonserver.direktiv-services-direktiv": dial tcp: lookup workflow-13418411225808356493-jsonserver.direktiv-services-direktiv on 10.43.0.10:53: no such host_

Thank you in advance!

**Comment by jensg-st** [comment]
Hi,

we have a couple of examples here: https://github.com/direktiv/direktiv-apps/tree/main/examples. They are implementing a simple "Hello World" scenario but it should get you going. 

The documentation is probably helpful too: https://docs.direktiv.io/v0.5.10/getting_started/making-functions/

The basic concept is to have a listener on port 8080 which receives the JSON request from Direktiv. The listener just has to respond to it with JSON and can potentially respond with errors too. 

If you are using the local docker container for testing you can use the registry installed in that container: https://docs.direktiv.io/v0.5.10/environment/direktiv-development-environment/ and push images to *localhost:31212/myapp*

Please feel free to ask a question if that does not get you started with your custom containers.

Thanks

**Comment by guojian83** [comment]
Thanks. That's very helpful!

**Comment by guojian83** [comment]
Actually may I reopen this as I was not able to get a sample working locally using docker container.
I chose the dotnet container and pushed to the local registry localhost:31212.
Here is my sample yaml file:
`id: mycontainer
functions:
- id: jsonserver
  image: localhost:31212/dotnetservice
  type: reusable
states:
- id: jsonserver
  type: action
  action:
    function: jsonserver
    input:
      name: "Jian"
  transform: 'jq(.return)'
  transition: logger
- id: logger
  type: noop
  log: 'jg(.)'
`

Can you spot any problem with my settings?

Regards,
J

**Comment by jensg-st** [comment]
Hi,

there are two little issues here. 

**1. We implemented a bug with the direktiv-kube container v0.5.10 and you found it :1st_place_medal:**

We have migrated Knative from 0.25 to 1.0 in the last release. The direktiv-kube container got updated too but there was something missing in the configuration so it can not pull the images from the local docker registry. We have updated the latest version to fix it. Either you have to stop the container, delete the image and re-pull it for the fix or we have pushed a version v0.5.10a. The following command should pull the fixed version:

```
docker run --privileged -p 8080:80 -p 31212:31212  -ti direktiv/direktiv-kube:v0.5.10a
```

But as I said you can delete the old image too and just run latest. That should work too. Sorry for that. We tested it with a different container and it works fine now.

**2. jq instead of jq**

The last log line has a typo. But that is just a small one.

**Comment by guojian83** [comment]
Thanks for the quick response. I have updated the docker image version, however, it still ran into the same error when invoking the dotnet container.
Anything else I can do to troubleshoot?

**Comment by jensg-st** [comment]
Hi,

Maybe I should have asked what the actual problem is?

**Comment by guojian83** [comment]
I am not sure if there are other logs I can look for. Right now the instance details page showed the same error as I started this thread.

**Comment by jensg-st** [comment]
There are two ways to find out what is not working with a function. 

1. User Interface

On the right side of the user interface you should see the function(s) used by that workflow. In this case it is only one so you should see only one in that list. I have highlighted it in the screenshot. The red dot usually turns green after downloading and starting a workflow. If you have an empty list, just run the workflow once to trigger the creation of the function because they are on demand. You can click on that function too to see details why it is not turning red. Pleas let me know what the errors are you are seeing on the detail page. 

![sc1](https://user-images.githubusercontent.com/10879611/143982652-cbc32666-16a2-457b-ab9c-df6f1db1857f.png)

That is one reason why we are getting a new UI in January. This functionality is not obvious :)

2. Kubectl

If you are  interested in the internals you can use kubectl too. For this you need to go to a shell in the container:

```
docker exec -it MY_CONTAINER_NAME /bin/bash
```

The services are based on Knative so they are called ksvc. Because you have only one the following command should show what is wrong with the service:

```
kubectl describe ksvc -A
```

This should report the same errors what the UI is showing. Just a preference.

**Comment by guojian83** [comment]
Ok great. Got it working now. Its simply running out of resource in local docker.
